language: ruby

script: build.sh

deploy:
  skip_cleanup: true
  provider: script
  script: deploy.sh
  on:
    branch: deploy

env:
  global:
    secure: bMTQBpghYZxdg78N/s8ZvKtpTXASmSrEw+VIm6U6PtN2KSkpBTeAAaJCva4i9ME2wcDlfQwDNcWLiGbJQj5SWbib8XFYsoSEG53+HPIyPyBu1Tn718bL1M4I/udaQCVP88YdQrn+ar8k14M3viYRBAihy0bc4b7bJGwHWG6sUQiht6zKrT8cKvny+iU5Nsyrdbvn2pQxOqNEjobULua2AEqCUxnPg+xaWs0RKwGJ+WVPga4jhe2Gf9GkjfBklwKc3lrtRqFrvmpySiTAW7z2XBHLn73JAuqzGAk+H9TyMU2n2Z/GgBJmxqtTlyH8qJ216MSw/9MQsBgrFRl9sI/8voZfb0sVlmSuajvkmLy283FvbjcMZONBsgtjunaOzH5CfDIGrEvcjjo4gdkOzoiIbucOB7H4nsC1hP0JdoqT+o2Lz7OGHqZ6eChXsihJdftXJvFPmv38ZuKQz+1x8rn65LEy3oZGrW9DtYUtiOOyd5fxxe5DhuJpd2cMoWofp1ecrCyZq2hTpEP/68wn+IIXjvxgNkDQEtxFkh6GMCd9yLIL/s//Bhxxy7vkamYjL//QSZ+zQV/qNQwW1V12TJHTO7xNEevlUDziW01WsLzvnffEw+bg0qW3mrm4wercVgf40Q/xj2EUV5Nv+zkEhsr9xC8v7sW9oCyv0w+POVeqva4=
