# Site settings
title: Michael Sobrepera
email: mjsobrep@live.com
description: A site about stuff that I (Michael Sobrepera) work on, think, enjoy, etc...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.michaelsobrepera.com" # the base hostname & protocol for your site
twitter_username: m_sobrepera
github_username:  mjsobrep

# Build settings
markdown: kramdown

permalink: none
ignore: /subl